# Artificial Neural Network

### Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras


## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dset = pd.read_excel('Folds5x2_pp.xlsx')
X = dset.iloc[:,:-1].values
y = dset.iloc[:,-1].values

In [3]:
X, y

(array([[  14.96,   41.76, 1024.07,   73.17],
        [  25.18,   62.96, 1020.04,   59.08],
        [   5.11,   39.4 , 1012.16,   92.14],
        ...,
        [  31.32,   74.33, 1012.92,   36.48],
        [  24.48,   69.45, 1013.86,   62.39],
        [  21.6 ,   62.52, 1017.23,   67.87]]),
 array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28]))

### Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [5]:
X_train, y_train

(array([[  11.22,   43.13, 1017.24,   80.9 ],
        [  13.67,   54.3 , 1015.92,   75.42],
        [  32.84,   77.95, 1014.68,   45.8 ],
        ...,
        [  16.81,   38.52, 1018.26,   75.21],
        [  12.8 ,   41.16, 1022.43,   86.19],
        [  32.32,   67.9 , 1006.08,   37.93]]),
 array([473.93, 467.87, 431.97, ..., 459.01, 462.72, 428.12]))

In [6]:
X_test, y_test

(array([[  28.66,   77.95, 1009.56,   69.07],
        [  17.48,   49.39, 1021.51,   84.53],
        [  14.86,   43.14, 1019.21,   99.14],
        ...,
        [  12.24,   44.92, 1023.74,   88.21],
        [  27.28,   47.93, 1003.46,   59.22],
        [  17.28,   39.99, 1007.09,   74.25]]),
 array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28]))

### Feature Scaling:

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Defining the build_ann that builds diff ANN with diff combinations of hyperParameters:

### importing necessary libraries:

In [8]:
from sklearn.model_selection import GridSearchCV

from keras.wrappers.scikit_learn import KerasRegressor
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten, Embedding, LeakyReLU, BatchNormalization, Dropout
from keras.activations import relu, sigmoid

### Defining create_ann that will build diff ANNs with diff combinations of hyperParameters:

In [9]:
def create_ann(layers, activation):
  ann = Sequential()

  for i,nodes in enumerate(layers):
    if i == 0: # adds Input layer and 1st Hidden Layer 
      ann.add(Dense(nodes, input_dim=X_train.shape[1]))
      ann.add(Activation(activation))
      ann.add(Dropout(0.3))
    else: # adds further Hidden Layers as specified
      ann.add(Dense(nodes))
      ann.add(Activation(activation))
      ann.add(Dropout(0.3))
    
  # add Output Layer:
  ann.add(Dense(
        units=1, # output neuron
        activation='linear' 
        ))
    
  # Compiling ANN:
  ann.compile(
      optimizer='adam',
      loss='mse',
      metrics=['mse']
  )

  # return ann:
  return ann

### Calling create_ann() with diff combinations of hyperParameters:

In [ ]:
ann = KerasRegressor(build_fn=create_ann, verbose=0)

# params:
layers = [(10,), (20,),]
activation = ['sigmoid', 'relu']
batch_sizes = [32, 64, ]
no_epochs = [
  
  
  
  
  
  -
  hyper50, 100,]

params_dict = dict(layers=layers, 
                   activation=activation,
                   batch_size=batch_sizes,
                   epochs=no_epochs
                   )

grid = GridSearchCV(estimator=ann,
                    param_grid=params_dict,
                    cv=5
                    )


grid_result = grid.fit(X_train, y_train)

### GridSearch best Results:

In [ ]:
# GridSearchCV 's best Results:

print("Best Score: ",grid_result.best_score_)
print("Best Params: ",grid_result.best_params_)

### Predicting the results of the Grid Results:

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(
    np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1)
)

# confusion matrix and accuracy:

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_pred, y_test)
print(cm)

accu_score = accuracy_score(y_pred, y_test)
print(accu_score)